export const IMAGES = {
  logo: "/images/logo/logo-white.png",
  logoBlack: "/images/logo/logo-black.png",
  favicon: "/images/logo/favicon.png",

  banners: {
    homeHero: "/images/banners/home-hero.png",
    oneTimeCook: "/images/banners/one-time-cook.png",
    cookForMonth: "/images/banners/cook-for-month.png",
    chefForParty: "/images/banners/chef-for-party.png",
    investor: "/images/banners/home-hero.png",
    subscription: "/images/banners/cook-for-month.png",
    testimonial: "/images/banners/one-time-cook.png",
    joinChef: "/images/banners/cook-for-month.png",
    contact: "/images/banners/home-hero.png",
    section: "/images/banners/home-hero.png",
    blog: "/images/banners/home-hero.png",
    cooksTeam: "/images/banners/cook-for-month.png",
    signUp: "/images/banners/chef-for-party.png",
    partyCook: "/images/banners/chef-for-party.png",
    bestCooks: "/images/banners/cook-for-month.png",
    koustov: "/images/banners/one-time-cook.png",
    rectangle: "/images/banners/home-hero.png",
  },

  sliders: {
    slider1: "/images/sliders/slider1.png",
    slider2: "/images/sliders/slider2.png",
    slider3: "/images/sliders/slider3.png",
    slider4: "/images/sliders/slider4.png",
  },

  icons: {
    register: "/images/icons/register.svg",
    selectService: "/images/icons/select-service.svg",
    payment: "/images/icons/payment.svg",
    getCook: "/images/icons/get-cook.svg",
    healthy: "/images/icons/healthy.svg",
    tailored: "/images/icons/tailored.svg",
    professional: "/images/icons/professional.svg",
    timely: "/images/icons/timely.svg",
    assured30: "/images/icons/assured-30.svg",
    effortless: "/images/icons/effortless.svg",
    timeManagement: "/images/icons/time-management.svg",
    easyBooking: "/images/icons/easy-booking.svg",
    bartenders: "/images/icons/bartenders.svg",
    appStore: "/images/icons/app-store.svg",
    googlePlay: "/images/icons/google-play.svg",
  },

  gallery: [
    "/images/gallery/gallery-1.png",
    "/images/gallery/gallery-2.png",
    "/images/gallery/gallery-3.png",
    "/images/gallery/gallery-4.png",
    "/images/gallery/gallery-5.png",
    "/images/gallery/gallery-6.png",
  ],
};
